include "common";

def table($title; $head; $rows):
  if ($rows | length) == 0 then empty
  else
    "",
    "### \($title) (\($rows | length))",
    "",
    "| \($head | join(" | ")) |",
    "| \($head | map("---") | join(" | ")) |",
    ($rows[] | "| \(join(" | ")) |")
  end;

def enables: sort_by(.option) | map([(.option | code), (.sources | if . == [] then "default" else map(.source | code) | join(", ") end)]);

def scope($presets):
  table("Packages"; ["Package", "Version", "Source"];
    .packages | sort_by(srckey($presets), .name) | map([(.name | md), (.version | md), (.source | code)])),
  table("Modules"; ["Option", "Enabled by"]; .modules | enables),
  table("Programs"; ["Option", "Enabled by"]; .programs | enables),
  table("Services"; ["Option", "Enabled by"]; .services | enables),
  table("Containers"; ["Container", "Image", "Source"];
    .containers | sort_by(.name) | map([(.name | md), (.image | code), (.source | code)])),
  table("Units"; ["Unit", "Scope", "Source"];
    .units | sort_by(srckey($presets), .name) | map([(.name | code), .scope, (.source | split(", ") | map(code) | join(", "))]));

.presets as $presets
| "# \(.host)",
  "",
  "<!-- Generated by `just inventory --save`; edit the config, not this file. -->",
  "",
  "Presets: \($presets | map(code) | join(" · "))",
  "",
  "Sources are the files that defined each entry. Paths outside this repo are upstream modules (nixpkgs, home-manager, …); `default` means the option is on by default.",
  "",
  "## System",
  (.system | scope($presets)),
  (.users | to_entries[] | "", "## User `\(.key)`", (.value | scope($presets)))
