include "common";

# Input: array of host inventories. $skipped: hosts that failed to evaluate.
. as $all
| ($all | map(.host)) as $hosts

# Entries tagged with host and where (S = system, H = home of any user), grouped into one row per key.
| def grid($entries; $key):
    $entries
    | group_by(.[$key])
    | map({
        key: .[0][$key],
        extra: .[0].extra,
        sources: (map(.sources[]) | unique),
        cells: (group_by(.host) | map({key: .[0].host, value: (map(.where) | unique | join(" "))}) | from_entries)
      });

  def table($title; $note; $head; $rows):
    if ($rows | length) == 0 then empty
    else
      "",
      "## \($title)",
      "",
      (if $note == "" then empty else $note, "" end),
      "| \(($head + $hosts) | join(" | ")) |",
      "| \(($head + $hosts) | map("---") | join(" | ")) |",
      ($rows[] | . as $r | "| \(($r.cols + ($hosts | map($r.cells[.] // ""))) | join(" | ")) |")
    end;

  def scopes: [{s: .system, where: "S"}] + [.users[] | {s: ., where: "H"}];

  def enabled_rows($field; $repo_only):
    grid([$all[] | .host as $h | scopes[] | .where as $w | .s[$field][]
          | select(($repo_only | not) or from_repo)
          | {key: .option, host: $h, where: $w, sources: [.sources[] | select(.upstream | not) | .source]}]; "key")
    | map({cols: [(.key | code), (.sources | map(code) | join(", "))], cells});

  "# Inventory",
  "",
  "<!-- Generated by `just inventory --all --save`; edit the config, not this file. -->",
  "",
  "What each host installs and enables. Per host, with every source file: \($hosts | map("[\(.)](\(.).md)") | join(" · ")).",
  "",
  "`S` = system, `H` = home-manager (any user).",
  (if ($skipped | length) > 0
   then "", "> [!WARNING]", "> Failed to evaluate, so missing here: \($skipped | map(code) | join(", "))."
   else empty end),

  table("Presets"; ""; ["Preset"];
    [$all | map(.presets[]) | unique[] as $p
     | {cols: [($p | code)], cells: ($all | map({key: .host, value: (if .presets | index($p) then "✓" else "" end)}) | from_entries)}]),

  table("Packages"; "Packages declared in this repo; upstream module defaults are in the per-host files."; ["Package", "Source"];
    grid([$all[] | .host as $h | scopes[] | .where as $w | .s.packages[] | select(.upstream | not)
          | {key: .name, host: $h, where: $w, sources: [.source]}]; "key")
    | map({cols: [(.key | md), (.sources | map(code) | join(", "))], cells})),

  table("Modules"; ""; ["Option", "Enabled by"]; enabled_rows("modules"; false)),

  table("Programs"; "Only those enabled from this repo."; ["Option", "Enabled by"]; enabled_rows("programs"; true)),

  table("Services"; "Only those enabled from this repo."; ["Option", "Enabled by"]; enabled_rows("services"; true)),

  table("Containers"; ""; ["Container", "Image"];
    [$all[] | .host as $h | .system.containers[] | {key: .name, extra: .image, host: $h, where: "✓", sources: []}]
    | grid(.; "key")
    | map({cols: [(.key | code), (.extra | code)], cells})),

  table("Units"; "systemd units defined in this repo."; ["Unit", "Source"];
    grid([$all[] | .host as $h | scopes[] | .where as $w | .s.units[]
          | {key: "\(.name) (\(.scope))", host: $h, where: $w, sources: (.source | split(", "))}]; "key")
    | map({cols: [(.key | code), (.sources | map(code) | join(", "))], cells}))
